import Link from 'next/link';
import Head from 'next/head';

const Layout = ({ children }: { children: JSX.Element }) => (
  <div className="max-w-screen-lg mx-auto">
    <Head>
      <title>Weather Forecast</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <header className="mt-5 mb-12">
      <Link href="/">
        <a className="mb-4 text-6xl font-extrabold tracking-tight">Weather Forecast</a>
      </Link>
    </header>
    <main>{children}</main>
  </div>
);

export default Layout;
